"""initial schema

Revision ID: 3f691e646cea
Revises: 
Create Date: 2026-06-20 22:00:05.942882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f691e646cea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'commissions', 'users', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'commissions', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'users', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    # ### end Alembic commands ###
